PYTHON_EXECUTOR_ADDRESS: "localhost:9999"
MAIN_LLM_HOST: "http://localhost:8080"
EMBEDDING_LLM_HOST: "http://localhost:8081"
SUMMARIZATION_LLM_HOST: "http://localhost:8082"
MAX_TURNS: 5
RAG_RESULTS: 5
#CONTEXT_LENGTH: 131072
CONTEXT_LENGTH: 10

# --- Retry Logic ---
MAX_RETRIES: 5
RETRY_DELAY_SECONDS: 2