PYTHON_EXECUTOR_ADDRESS: "localhost:9999"
OLLAMA_HOST: "http://localhost:11434"
MAX_TURNS: 5
MODEL: "devstral:24b"
EMBEDDING_MODEL: "bge-large:335m"
SUMMARIZATION_MODEL: "qwen2.5:7b"
# EMBEDDING_MODEL: "nomic-embed-text:v1.5"
# SUMMARIZATION_MODEL: "phi3.5:8b"
RAG_RESULTS: 5