# --- Web Server Configuration ---
WEB_PORT: 5000  # Port for web server (default: 8080)

# --- Database Configuration ---
DATABASE_URL: "postgres://postgres:changeme@localhost:5432/stats_agent?sslmode=disable"

# --- Python Executor Configuration ---
PYTHON_EXECUTOR_ADDRESSES:
  - "localhost:9999"
  - "localhost:9998"
  - "localhost:9997"
  - "localhost:9996"
  - "localhost:9995"
PYTHON_EXECUTOR_COOLDOWN_SECONDS: 5      # Seconds to wait before retrying a failed executor
PYTHON_EXECUTOR_DIAL_TIMEOUT_SECONDS: 3  # TCP dial timeout to python executors
PYTHON_EXECUTOR_IO_TIMEOUT_SECONDS: 60   # Read/write timeout per execution
PYTHON_EXECUTOR_MAX_CONNECTIONS: 4       # Max simultaneous connections per executor

# --- LLM Server Configuration ---
MAIN_LLM_HOST: "http://localhost:8080"
EMBEDDING_LLM_HOST: "http://localhost:8081"
SUMMARIZATION_LLM_HOST: "http://localhost:8082"
MAX_TURNS: 30
RAG_RESULTS: 3
CONTEXT_LENGTH: 16384
#CONTEXT_LENGTH: 2048
CONTEXT_SOFT_LIMIT_RATIO: 0.5
CONSECUTIVE_ERRORS: 5
LLM_REQUEST_TIMEOUT: 300

# --- Retry Logic For Connecting to Llama.CPP ---
MAX_RETRIES: 5
RETRY_DELAY_SECONDS: 2

# --- Session Cleanup Configuration ---
CLEANUP_ENABLED: true
CLEANUP_INTERVAL: 24        # Run cleanup every 24 hours
SESSION_RETENTION_AGE: 168  # Delete sessions older than 7 days (168 hours)

# --- Rate Limiting Configuration ---
RATE_LIMIT_MESSAGES_PER_MIN: 20  # Max messages per session per minute
RATE_LIMIT_FILES_PER_HOUR: 10    # Max file uploads per session per hour
RATE_LIMIT_BURST_SIZE: 5         # Allow burst of N requests

# --- Retrieval Tuning ---
MAX_EMBEDDING_CHARS: 1000              # Max characters before a message is chunked for embeddings
MAX_EMBEDDING_TOKENS: 250              # Target token count per embedded chunk
EMBEDDING_TOKEN_SOFT_LIMIT: 450        # Token count that triggers truncation before embedding
EMBEDDING_TOKEN_TARGET: 400            # Target tokens when truncating for embeddings
MIN_TOKEN_CHECK_CHAR_THRESHOLD: 100    # Skip embedding token counting for short strings
MAX_HYBRID_CANDIDATES: 100             # Candidate limit when blending semantic/BM25 retrieval
HYBRID_SEMANTIC_WEIGHT: 0.7            # Weight assigned to semantic similarity during hybrid scoring
HYBRID_BM25_WEIGHT: 0.3                # Weight assigned to BM25 during hybrid scoring
RAG_CONTEXT_MAX_CHARS: 12000           # Hard cap on characters included in assembled context window
HYBRID_FACT_BOOST: 1.3                 # Multiplier applied to fact documents
HYBRID_SUMMARY_BOOST: 1.2              # Multiplier applied to summary documents
HYBRID_ERROR_PENALTY: 0.8              # Multiplier applied when content contains error text
SEMANTIC_SIMILARITY_THRESHOLD: 0.7  # Minimum cosine similarity for vector hits
BM25_SCORE_THRESHOLD: 0.10           # Minimum BM25+bonus score for text hits
ENABLE_METADATA_FALLBACK: true      # Enable metadata-based fallback search when hybrid results are empty
METADATA_FALLBACK_MAX_FILTERS: 3     # Limit number of auto-derived metadata filters

# --- PDF Processing Configuration ---
PDF_TOKEN_THRESHOLD: 0.75                 # Use 75% of context window for PDF content
PDF_FIRST_PAGES_PRIORITY: 3               # Keep first N pages if possible
PDF_ENABLE_TABLE_DETECTION: true          # Detect and mark tables in extracted text
PDF_SENTENCE_BOUNDARY_TRUNCATE: true      # Truncate at sentence boundaries for better context
