# --- Logging Configuration ---
LOG_LEVEL: debug # Options: debug, info, warn, error (default: info)

# --- Web Server Configuration ---
WEB_PORT: 5000 # Port for web server

# --- Python Executor Configuration ---
PYTHON_EXECUTOR_ADDRESSES:
  - "localhost:9999"
  - "localhost:9998"
  - "localhost:9997"
  - "localhost:9996"
  - "localhost:9995"
PYTHON_EXECUTOR_COOLDOWN_SECONDS: 5      # Seconds to wait before retrying a failed executor
PYTHON_EXECUTOR_DIAL_TIMEOUT_SECONDS: 3  # TCP dial timeout to python executors
PYTHON_EXECUTOR_IO_TIMEOUT_SECONDS: 60   # Read/write timeout per execution
PYTHON_EXECUTOR_MAX_CONNECTIONS: 4       # Max simultaneous connections per executor

# --- LLM Server Configuration ---
MAIN_LLM_HOST: "http://localhost:8080"
EMBEDDING_LLM_HOST: "http://localhost:8081"
SUMMARIZATION_LLM_HOST: "http://localhost:8082"
MAX_TURNS: 30
RAG_RESULTS: 10
CONTEXT_LENGTH: 16384
#CONTEXT_LENGTH: 2048
CONTEXT_SOFT_LIMIT_RATIO: 0.75
CONSECUTIVE_ERRORS: 5
LLM_REQUEST_TIMEOUT: 300

# --- Retry Logic For Connecting to Llama.CPP ---
MAX_RETRIES: 5
RETRY_DELAY_SECONDS: 2

# --- Session Cleanup Configuration ---
CLEANUP_ENABLED: true
CLEANUP_INTERVAL: 24        # Run cleanup every 24 hours
SESSION_RETENTION_AGE: 168  # Delete sessions older than 7 days (168 hours)

# --- Rate Limiting Configuration ---
RATE_LIMIT_MESSAGES_PER_MIN: 20  # Max messages per session per minute
RATE_LIMIT_FILES_PER_HOUR: 10    # Max file uploads per session per hour
RATE_LIMIT_BURST_SIZE: 5         # Allow burst of N requests

# --- Retrieval Tuning ---
MAX_EMBEDDING_TOKENS: 450              # BGE-large-en-v1.5 token limit (deprecated - use specific chunk configs below)
EMBEDDING_TOKEN_SOFT_LIMIT: 512        # BGE-large-en-v1.5 hard limit (for safety check only)
EMBEDDING_TOKEN_TARGET: 480            # Target tokens when truncating for embedding generation
MIN_TOKEN_CHECK_CHAR_THRESHOLD: 5     # Skip BGE tokenization for strings shorter than this

# --- Chunking Configuration ---
CONVERSATION_CHUNK_SIZE: 1500          # Tokens per conversation chunk (stored, not just embedded)
CONVERSATION_CHUNK_OVERLAP: 0.20       # Overlap ratio for conversation chunks (20% = ~300 tokens)
DOCUMENT_CHUNK_SIZE: 3500              # Tokens per document chunk (PDFs, Word docs, etc.)
DOCUMENT_CHUNK_OVERLAP: 0.0            # Overlap ratio for document chunks (0 = no overlap)
MAX_HYBRID_CANDIDATES: 200             # Candidate limit when blending semantic/BM25 retrieval
HYBRID_SEMANTIC_WEIGHT: 0.7            # Weight assigned to semantic similarity during hybrid scoring
HYBRID_BM25_WEIGHT: 0.3                # Weight assigned to BM25 during hybrid scoring
HYBRID_FACT_BOOST: 1.3                 # Multiplier applied to fact documents
HYBRID_SUMMARY_BOOST: 1.2              # Multiplier applied to summary documents
HYBRID_ERROR_PENALTY: 0.8              # Multiplier applied when content contains error text
SEMANTIC_SIMILARITY_THRESHOLD: 0.45  # Minimum cosine similarity for vector hits
BM25_SCORE_THRESHOLD: 0.10           # Minimum BM25+bonus score for text hits
ENABLE_METADATA_FALLBACK: true      # Enable metadata-based fallback search when hybrid results are empty
METADATA_FALLBACK_MAX_FILTERS: 3     # Limit number of auto-derived metadata filters

# --- PDF Processing Configuration ---
PDF_TOKEN_THRESHOLD: 0.75                 # Use 75% of context window for PDF content
PDF_FIRST_PAGES_PRIORITY: 3               # Keep first N pages if possible
PDF_ENABLE_TABLE_DETECTION: true          # Detect and mark tables in extracted text
PDF_SENTENCE_BOUNDARY_TRUNCATE: true      # Truncate at sentence boundaries for better context

# --- PDF Extractor Service (pdfplumber microservice) ---
PDF_EXTRACTOR_URL: "http://localhost:9001"  # URL of the pdfplumber extraction service
PDF_EXTRACTOR_ENABLED: true                  # Enable high-quality pdfplumber extraction
PDF_EXTRACTOR_TIMEOUT: 30                    # Timeout in seconds for PDF extraction requests
## Tuning parameters (appended as query args to PDF_EXTRACTOR_URL)
PDF_EXTRACTOR_MODE: "words"          # "pdfminer" or "words"; empty lets service choose
PDF_EXTRACTOR_WORD_MARGIN: 0.35      # pdfminer LAParams word_margin
PDF_EXTRACTOR_CHAR_MARGIN: 2.0       # pdfminer LAParams char_margin
PDF_EXTRACTOR_LINE_MARGIN: 0.2       # pdfminer LAParams line_margin
PDF_EXTRACTOR_BOXES_FLOW: 0.5        # pdfminer LAParams boxes_flow
PDF_EXTRACTOR_USE_TEXT_FLOW: true    # pdfplumber extract_words(use_text_flow)
PDF_EXTRACTOR_X_TOLERANCE: 1.0       # pdfplumber x_tolerance
PDF_EXTRACTOR_Y_TOLERANCE: 3.0       # pdfplumber y_tolerance

# --- PDF Page Cleanup ---
# Threshold for considering a line a repeating header/footer (fraction of pages)
PDF_HEADER_FOOTER_REPEAT_THRESHOLD: 0.6
# Remove trailing reference sections (detected by heading or citation density)
PDF_REFERENCES_TRIM_ENABLED: true
# Proportion of lines that look like citations to consider a page a reference page
PDF_REFERENCES_CITATION_DENSITY: 0.7
