PYTHON_EXECUTOR_ADDRESS: "localhost:9999"
MAIN_LLM_HOST: "http://localhost:8080"
EMBEDDING_LLM_HOST: "http://localhost:8081"
SUMMARIZATION_LLM_HOST: "http://localhost:8082"
MAX_TURNS: 10
RAG_RESULTS: 5
CONTEXT_LENGTH: 16384

# --- Retry Logic For Connecting to Llama.CPP ---
MAX_RETRIES: 5
RETRY_DELAY_SECONDS: 2